### ISSUE TITLE
Severe problem with switch move for simulations with more than 2 guests

### ISSUE THREAD

**Issue by BurnerJ** [peteboyd/gcmc#1]
Seems there is a bug in the routine for the switch move for simulations _where there are more than two components_. This was observed for many GCMC simulations for a screening at the following conditions: 573 K, 16.5 bar H2, 3.6 bar CO2, 4.5 bar CO, using 10,000 equilibration cycles and 10,000 production cycles. The main issue is we get enormous uptakes for a single component and almost nothing for the other components, and in addition to this, the uptakes obtained using the "switch" move are not consistent (they predict totally different uptakes between trials). Using FastMC version 1.4.0 with only deletion, insertion, and displacement moves, we get the following uptakes for this particular MOF (which we treat as being the correct uptakes, in units of number of guests per simulation cell):
 
H2: 5.06, CO2: 1.65, CO: 1.70

The tests I have run to investigate this are summarized in an attached image in a table. I have attached sample CONFIG, CONTROL, and FIELD files (where the CONTROL file specifies all six moves together, and should yield an erroneous result):
[CONTROL.txt](https://github.com/uowoolab/FastMC/files/10180043/CONTROL.txt)
[FIELD.txt](https://github.com/uowoolab/FastMC/files/10180044/FIELD.txt)
[OUTPUT.txt](https://github.com/uowoolab/FastMC/files/10180045/OUTPUT.txt)
[CONFIG.txt](https://github.com/uowoolab/FastMC/files/10180046/CONFIG.txt)

![FastMC switch bug](https://user-images.githubusercontent.com/65910037/206297527-485f30fc-e6c1-4266-8644-8a85bf381aec.JPG)

**Comment by peteboyd** [comment]
@BurnerJ Thanks for the detailed issue, very helpful when trying to debug. I can reproduce the problem, but haven't solved it yet. When I let the subroutine `mc_switch` run but always set `accepted=.false.` so that no moves actually become accepted, the error persists. This suggests there's something wrong with the bookkeeping of the molecules and/or energy arrays when these moves are rejected.

**Comment by peteboyd** [comment]
@BurnerJ After making the commits, I ran your sim a couple of times and got the 'reasonable' uptakes. But re-open this if the results become absurd again. Thanks!
